var Printing = [{
	"type": "FeatureCollection",
																					
	"features": [
	{ "type": "Feature", "properties": { "Id": 0, "LOCATION": "Jolly Giant Commons", "HTML": "<table class='PrintContent' border='0'><tr><td><p class='PrintLocationTitles' style='font-size: 23px;'>Jolly Giant <br>Commons</p></td><td></td></tr><tr><td><p class='PrintSubTitles'>1st Floor Rec Room</p></td><td><img src='images/QuickPrintKiosk.png' style='width: 35px;  padding-right: 10px; vertical-align: bottom;'/></td></tr></table>" }, "geometry": { "type": "Point", "coordinates": [ -124.07849868103435, 40.878877452955628 ] } },
	{ "type": "Feature", "properties": { "Id": 0, "LOCATION": "University Center", "HTML": "<table class='PrintContent' border='0'><tr><td><p class='PrintLocationTitles' style='font-size: 23px;'>University <br>Center</p></td><td></td></tr><tr><td><p class='PrintSubTitles'>South Lounge</p></td><td><img src='images/QuickPrintKiosk.png' style='width: 35px;  padding-right: 10px; vertical-align: bottom;'/></td></tr></table>" }, "geometry": { "type": "Point", "coordinates": [ -124.07848202480729, 40.877493796380541 ] } },
	{ "type": "Feature", "properties": { "Id": 0, "LOCATION": "Founders Hall", "HTML": "<table class='PrintContent' border='0'><tr><td style='padding: 0px;'><p class='PrintLocationTitles' style='font-size: 23px;'>Founders Hall</p></td><td></td></tr><tr><td style='padding: 0px;'><p class='PrintSubTitles'>Room 143</p></td><td><img src='images/Black&WhitePrinter.png' style='width: 35px;  padding-right: 10px; vertical-align: bottom;'/><br></td></tr><tr><td style='padding: 0px;'><p class='PrintSubTitles'>Northwest<br>1st Floor Stairwell</p></td><td><img src='images/QuickPrintKiosk.png' style='width: 35px;  padding-right: 10px; vertical-align: bottom;'/></td></tr></table>" }, "geometry": { "type": "Point", "coordinates": [ -124.07744695926961, 40.87713390290336 ] } },
	{ "type": "Feature", "properties": { "Id": 0, "LOCATION": "Siemens Hall", "HTML": "<table class='PrintContent' border='0'><tr><td><p class='PrintLocationTitles' style='font-size: 23px;'>Siemens Hall</p></td><td></td></tr><tr><td><p class='PrintSubTitles'>East <br>Outside of 130C</p></td><td><img src='images/QuickPrintKiosk.png' style='width: 35px;  padding-right: 10px; vertical-align: bottom;'/></td></tr></table>" }, "geometry": { "type": "Point", "coordinates": [ -124.0789727886398, 40.876982212264238 ] } },
	{ "type": "Feature", "properties": { "Id": 0, "LOCATION": "Library", "HTML": "<table class='PrintContent' border='0'><tr><td><p class='PrintLocationTitles' style='font-size: 23px;'>Library</p></td><td></td></tr><tr><td><p class='PrintSubTitles'>Library 101</p></td><td><div><img src='images/Combined_Printing_Icons.png' style='width: 45px; margin: 0 auto; vertical-align: bottom;'/></div></td></tr><tr><td><p class='PrintSubTitles'>Library 121<br>and Lib 122</p></td><td><div><img src='images/OpenLab2.png' style='width: 40px; margin: 0 auto; vertical-align: bottom;'/></div></td></tr><tr><td><p class='PrintSubTitles'>Library 201</p></td><td><div style='padding-left: 9px;'><img src='images/Black&WhitePrinter.png' style='width: 25px; vertical-align: bottom;'/></div></td></tr><tr><td><p class='PrintSubTitles'>Library 301</p></td><td><div style='padding-left: 9px;'><img src='images/Black&WhitePrinter.png' style='width: 25px; vertical-align: bottom;'/></div></td></tr></table>" }, "geometry": { "type": "Point", "coordinates": [ -124.08016549346915, 40.876527140346809 ] } },
	{ "type": "Feature", "properties": { "Id": 0, "LOCATION": "Gist Hall", "HTML": "<table class='PrintContent' border='0'><tr><td><p class='PrintLocationTitles' style='font-size: 23px;'>Gist Hall</p></td><td></td></tr><tr><td><p class='PrintSubTitles'>2nd Floor by <br>Vending Machines</p></td><td><img src='images/QuickPrintKiosk.png' style='width: 35px;  padding-right: 10px; vertical-align: bottom;'/></td></tr></table>" }, "geometry": { "type": "Point", "coordinates": [ -124.07913935091011, 40.875503972114174 ] } },
	{ "type": "Feature", "properties": { "Id": 0, "LOCATION": "Recreation & Wellness Center", "HTML": "<div class='PrintContent' style='width: 190px;'><table border='0'><tr><td><p class='PrintLocationTitles' style='font-size: 23px;'>Recreation & <br>Wellness Center</p></td><td></td></tr></table><table border='0' style='width: 180px'><tr><td><p class='PrintSubTitles'>Wellness<br>Center Lobby</p></td><td><img src='images/Black&WhitePrinter.png' style='width: 35px; padding-right: 10px; vertical-align: bottom;'/></td></tr></table></div>" }, "geometry": { "type": "Point", "coordinates": [ -124.07634050990205, 40.875548587008026 ] } },
	{ "type": "Feature", "properties": { "Id": 0, "LOCATION": "Kinesiology & Athletics", "HTML": "<table class='PrintContent' border='0'><tr><td><p class='PrintLocationTitles' style='font-size: 23px;'>Kinesiology <br>& Athletics</p></td><td></td></tr><tr><td><p class='PrintSubTitles'>1st Floor by <br>Vending Machines</p></td><td><img src='images/QuickPrintKiosk.png' style='width: 35px;  padding-right: 10px; vertical-align: bottom;'/></td></tr></table>" }, "geometry": { "type": "Point", "coordinates": [ -124.0751567280515, 40.874694955372085 ] } },
	{ "type": "Feature", "properties": { "Id": 0, "LOCATION": "BSS", "HTML": "<div class='PrintContent' style='width: 210px;'><table><tr><td><p class='PrintLocationTitles' style='font-size: 23px;'>Behavorial & Social <br>Sciences</p></td><td></td></tr></table><table border='0' width='210px;'><tr><td><p class='PrintSubTitles'>Room 316</p></td><td><img src='images/ColorPrinter.png' style='width: 35px; height: 33px; padding-left: 45px; padding-right: 10px; vertical-align: bottom;'/><img src='images/Black&WhitePrinter.png' style='width: 35px; vertical-align: bottom;'/></td></tr></table></div>" }, "geometry": { "type": "Point", "coordinates": [ -124.07723280777921, 40.872937128553801 ] } },
	{ "type": "Feature", "properties": { "Id": 0, "LOCATION": "Forestry", "HTML": "<table class='PrintContent' border='0'><tr><td><p class='PrintLocationTitles' style='font-size: 23px;'>Forestry</p></td><td></td></tr><tr><td><p class='PrintSubTitles'>Hallway by <br>Vending Machines</p></td><td><img src='images/QuickPrintKiosk.png' style='width: 35px;  padding-right: 10px; vertical-align: bottom;'/></td></tr></table>" }, "geometry": { "type": "Point", "coordinates": [ -124.0771703469278, 40.873505224869021 ] } },
	{ "type": "Feature", "properties": { "Id": 0, "LOCATION": "Natural Resources", "HTML": "<table class='PrintContent' border='0'><tr><td><p class='PrintLocationTitles' style='font-size: 23px;'>Natural <br>Resources</p></td><td></td></tr><tr><td><p class='PrintSubTitles'>Student Lounge</p></td><td><img src='images/QuickPrintKiosk.png' style='width: 35px;  padding-right: 10px; vertical-align: bottom;'/></td></tr></table>" }, "geometry": { "type": "Point", "coordinates": [ -124.07797638934358, 40.873413020754995 ] } }
	]
}];